document.write("<div id=\"idBox\" class=\"lightbox\" style=\"display:none;\">");document.write("	<div id=\"boxMain\">");document.write("		<div id=\"boxTopTitle\">");document.write("			<span id=\"boxName\">显示框</span>");document.write("			<span id=\"boxClose\" title=\"关闭\" onclick=\"box.Close();\">×</spab>");document.write("		</div>");document.write("		<div id=\"boxContent\">");document.write("			<iframe id=\"showiframe\" src=\"\" frameborder=\"0\" style=\"width:100%;\"></iframe>");document.write("		</div>");document.write("	</div>");document.write("</div>");function loadCss(url){var link=document.createElement("link");link.type="text/css";link.rel="stylesheet";link.href=url;document.getElementsByTagName("head")[0].appendChild(link);}
var isIE=(document.all)?true:false;var isIE6=isIE&&([/MSIE (\d+)\.0/i.exec(navigator.userAgent)][0][1]==6);var $G=function(id){return "string"==typeof id?document.getElementById(id):id;};var Class={create:function(){return function(){this.initialize.apply(this,arguments);}}}
var Extend=function(destination,source){for(var property in source){destination[property]=source[property];}}
var Bind=function(object,fun){return function(){return fun.apply(object,arguments);}}
var Each=function(list,fun){for(var i=0,len=list.length;i<len;i++){fun(list[i],i);}};var Contains=function(a,b){return a.contains?a!=b&&a.contains(b):!!(a.compareDocumentPosition(b)&16);}
var OverLay=Class.create();OverLay.prototype={initialize:function(options){this.SetOptions(options);this.Lay=$G(this.options.Lay)||document.body.insertBefore(document.createElement("div"),document.body.childNodes[0]);this.Color=this.options.Color;this.Opacity=parseInt(this.options.Opacity);this.zIndex=parseInt(this.options.zIndex);with(this.Lay.style){display="none";zIndex=this.zIndex;left=top=0;position="fixed";width=height="100%";}
if(isIE6){this.Lay.style.position="absolute";this._resize=Bind(this,function(){this.Lay.style.width=Math.max(document.documentElement.scrollWidth,document.documentElement.clientWidth)+"px";this.Lay.style.height=Math.max(document.documentElement.scrollHeight,document.documentElement.clientHeight)+"px";});this.Lay.innerHTML='<iframe style="position:absolute;top:0;left:0;width:100%;height:100%;filter:alpha(opacity=0);"></iframe>'}},SetOptions:function(options){this.options={Lay:null,Color:"#000",Opacity:50,zIndex:2147483640};Extend(this.options,options||{});},Show:function(){if(isIE6){this._resize();window.attachEvent("onresize",this._resize);}
with(this.Lay.style){filter="alpha(opacity:"+this.Opacity+")";opacity=this.Opacity/100;backgroundColor=this.Color;display="block";}},Close:function(){this.Lay.style.display="none";if(isIE6){window.detachEvent("onresize",this._resize);}}};var LightBox=Class.create();LightBox.prototype={initialize:function(box,options){this.Box=$G(box);this.OverLay=new OverLay(options);this.SetOptions(options);this.Fixed=!!this.options.Fixed;this.Over=!!this.options.Over;this.Center=!!this.options.Center;this.onShow=this.options.onShow;this.Box.style.zIndex=this.OverLay.zIndex+99990;if(isIE6){this._top=this._left=0;this._select=[];this._fixed=Bind(this,function(){this.Center?this.SetCenter():this.SetFixed();});}},SetOptions:function(options){this.options={Over:true,Fixed:true,Center:true,onShow:function(){}};Extend(this.options,options||{});},SetFixed:function(){this.Box.style.top=document.documentElement.scrollTop-this._top+this.Box.offsetTop+"px";this.Box.style.left=document.documentElement.scrollLeft-this._left+this.Box.offsetLeft+"px";this._top=document.documentElement.scrollTop;this._left=document.documentElement.scrollLeft;},SetCenter:function(){this.Box.style.marginTop=document.documentElement.scrollTop-this.Box.offsetHeight/2+"px";this.Box.style.marginLeft=document.documentElement.scrollLeft-this.Box.offsetWidth/2+"px";},Show:function(options){if(typeof options=='undefined')options={width:'800px',height:'500px'};if(typeof options!='undefined'&&options.height){if(parseInt(options.height)<($(window).height()-130))
document.getElementById('showiframe').height=options.height;else
document.getElementById('showiframe').height=$(window).height()-130;}
if(typeof options!='undefined'&&options.width){$("#idBox").css("max-width",options.width);var idBoxWidth=$("#idBox").width();var idBoxHeight=$("#idBox").height();$("#idBox").css("margin-left",-idBoxWidth/2);$("#idBox").css("margin-top",-idBoxHeight/2);}
this.Over&&this.OverLay.Show();this.Box.style.display="";if(isIE6){if(!this.Over){this._select.length=0;Each(document.getElementsByTagName("select"),Bind(this,function(o){if(!Contains(this.Box,o)){o.style.visibility="hidden";this._select.push(o);}}))}
this.Center?this.SetCenter():this.Fixed&&this.SetFixed();this.Fixed&&window.attachEvent("onscroll",this._fixed);}
this.onShow();},Close:function(){this.Box.style.display="none";this.OverLay.Close();document.getElementById("idBox").style.height='';if(isIE6){window.detachEvent("onscroll",this._fixed);Each(this._select,function(o){o.style.visibility="visible";});}}};if(typeof loadExtendFileCache==='undefined'){var loadExtendFileCache={'css':[],'js':[]};}
if(typeof loadExtendFile==='undefined'){function loadExtentFile(filePath,fileType){if(fileType=="js"){if(loadExtendFileExists(filePath,fileType))return false;var oJs=document.createElement('script');oJs.setAttribute("type","text/javascript");oJs.setAttribute("src",filePath);document.getElementsByTagName("head")[0].appendChild(oJs);loadExtendFileCache['js'].push(filePath);}else if(fileType=="css"){if(loadExtendFileExists(filePath,fileType))return false;var oCss=document.createElement("link");oCss.setAttribute("rel","stylesheet");oCss.setAttribute("type","text/css");oCss.setAttribute("href",filePath);document.getElementsByTagName("head")[0].appendChild(oCss);loadExtendFileCache['css'].push(filePath);}}}
if(typeof loadExtendFileExists==='undefined'){function loadExtendFileExists(filePath,fileType){if(typeof loadExtendFileCache[fileType]=='undefined')return false;for(var i=0;i<loadExtendFileCache[fileType].length;i++){if(loadExtendFileCache[fileType][i]==filePath)return true;}
return false;}}
function GetUrlPara(){var url=document.location.toString();var arrUrl=url.split("?");var paras='';if(arrUrl.length>1){var para=arrUrl[1];var arrUrl2=para.split("&");arrUrl2.forEach(function(e){if(e.indexOf("mod=")>=0||e.indexOf("act=")>=0){return;}else{paras=e+"&";}})}
return paras;}
function goserverurl(sys_url,DIY_JS_SERVER,DIY_WEBSITE_ID){var params=GetUrlPara();var serverUrl='http://'+DIY_JS_SERVER+'/sysTools.php?mod=viewsConn&idweb='+DIY_WEBSITE_ID+'&'+params+sys_url;var newserverUrl="<scr"+"ipt type='text/javascript' src="+serverUrl+"></scr"+"ipt>";$("body").append(newserverUrl);}
function price_format(s,n){n=n>0&&n<=20?n:2;s=parseFloat((s+"").replace(/[^\d\.-]/g,"")).toFixed(n)+"";var l=s.split(".")[0].split("").reverse(),r=s.split(".")[1];t="";for(i=0;i<l.length;i++){t+=l[i]+((i+1)%3==0&&(i+1)!=l.length?",":"");}
return t.split("").reverse().join("")+"."+r;}
function _RequestParamsStr(){var strHref=window.document.location.href;var intPos=strHref.indexOf('?');var strRight=strHref.substr(intPos+1);return strRight;}
function Request(strName){var arrTmp=_RequestParamsStr().split("&");for(var i=0,len=arrTmp.length;i<len;i++){var arrTemp=arrTmp[i].split("=");if(arrTemp[0].toUpperCase()==strName.toUpperCase()){if(arrTemp[1].indexOf("#")!=-1)arrTemp[1]=arrTemp[1].substr(0,arrTemp[1].indexOf("#"));return arrTemp[1];}}
return "";}
function ReqquestArray(strName){var arr_Return=[];var arrTmp=_RequestParamsStr().split("&");var s_Find=strName+"[";for(var i=0,len=arrTmp.length;i<len;i++){var arr_Temp=arrTmp[i].split("=");var posistion=arr_Temp[0].indexOf(s_Find);if(posistion==0){arr_Return.push(arr_Temp[1]);}}
return arr_Return;}
function RequestDict(strName){var arr_Return={};var arrTmp=_RequestParamsStr().split("&");var s_Find=strName+"[";for(var i=0,len=arrTmp.length;i<len;i++){var arr_Temp=arrTmp[i].split("=");var posistion=arr_Temp[0].indexOf(s_Find);if(posistion==0){var s_Key=arr_Temp[0].substr(s_Find.length);s_Key=s_Key.substr(0,s_Key.length-1);arr_Return[s_Key]=arr_Temp[1];}}
return arr_Return;}
function btnTop(){$("html,body").animate({scrollTop:"0px"},1000);}
function btnBottom(){var bodyH=$("html,body").height();$("html,body").animate({scrollTop:bodyH},1000);}
var box=new LightBox("idBox");